name: CI

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}
        submodules: recursive

    - uses: mfinelli/setup-imagemagick@v6

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install JS dependencies
      run: npm i
    
    - name: Build website
      run: npm run build
    
    - name: Run resize script
      working-directory: ./frontend/scripts
      run: ./resize.sh

    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        port: 22
        key: ${{ secrets.DEPLOY_SSHKEY }}
        source: "frontend/css/,frontend/data/,frontend/img/,frontend/js/,frontend/templates/,frontend/index.php,frontend/vendor/,frontend/lore/,frontend/node_modules/,frontend/favicon.ico"
        target: ${{ secrets.DEPLOY_TARGET }}
